#!/usr/bin/env bash

# Colors: FG (foreground), BG (background), HL (highlighted)
FG_COLOR="#bbbbbb"
BG_COLOR="#111111"
HLFG_COLOR="#111111"
HLBG_COLOR="#bbbbbb"
BORDER_COLOR="#222222"

ROFI_OPTIONS=(-theme ~/.config/rofi/powermenu.rasi)
ROFI_TEXT="Power Menu"

# Menu with keys/commands
declare -A menu=(
  [" Shutdown"]="systemctl poweroff"
  [" Reboot"]="systemctl reboot"
  [" Suspend"]="systemctl suspend"
  [" Hibernate"]="systemctl hibernate"
  [" Lock"]="$HOME/.config/i3/scripts/blur-lock"
  [" Logout"]="i3-msg exit"
  [" Cancel"]=""
)

menu_nrows=${#menu[@]}

rofi_colors=(-bc "${BORDER_COLOR}" -bg "${BG_COLOR}" -fg "${FG_COLOR}" -hlfg "${HLFG_COLOR}" -hlbg "${HLBG_COLOR}")

"$(printf '%s\n' "${!menu[@]}" | sort | rofi -dmenu -i -lines "${menu_nrows}" -p "${ROFI_TEXT}" "${rofi_colors[@]}" "${ROFI_OPTIONS[@]}")"
